### ISSUE TITLE
Transform ROIs error

### ISSUE THREAD

**Issue by NadiaHuisjes** [duderstadt-lab/mars-core#9] opened 2020-09-10 16:27 UTC
While testing the Transform ROIs command I stumbled upon the following error.

* When applying the following settings and ticking both the 'Colocalize' and 'Preview' box the error in the screenshot below was generated.
<img width="1194" alt="Screenshot 2020-09-10 at 17 34 59" src="https://user-images.githubusercontent.com/61824826/92755464-2205d500-f38c-11ea-89fb-ec7d565ea1f2.png">

**Comment by karlduderstadt** [comment] 2020-09-11 13:56
Hi @NadiaHuisjes,

Thanks for reporting this issue. This error was caused by when the region searched for colocalization was partially or fully out of bounds. That happens when Rois are transformed to locations that are out side the image area. Usually this doesn't occur because  only subregions are selected for a given color and, when transformed, they all remain within the image area.

I am closing the issue based on the commit above that prevents sampling in out of bounds regions and prevents the error, but transforming Rois to locations that are out of bounds may cause problems in other tools, like the Molecule Integrator. This has not been fully tested.

**Closed by karlduderstadt** 2020-09-11 13:56 UTC
